// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(layoutFFI)
    import layoutFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_layout_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_layout_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

/**
 * Arrowhead geometry at an edge's target end: a tip point plus two wing
 * vertices, ready to fill as a triangle.
 */
public struct FfiArrowhead {
    /**
     * Tip point where the arrow touches the target node boundary.
     */
    public var tip: FfiPoint
    /**
     * Tangent angle in radians (pointing in the direction of the edge flow).
     */
    public var angle: Float
    /**
     * Left wing endpoint.
     */
    public var left: FfiPoint
    /**
     * Right wing endpoint.
     */
    public var right: FfiPoint

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Tip point where the arrow touches the target node boundary.
         */ tip: FfiPoint,
        /* 
            * Tangent angle in radians (pointing in the direction of the edge flow).
            */ angle: Float,
        /* 
            * Left wing endpoint.
            */ left: FfiPoint,
        /* 
            * Right wing endpoint.
            */ right: FfiPoint
    ) {
        self.tip = tip
        self.angle = angle
        self.left = left
        self.right = right
    }
}

extension FfiArrowhead: Sendable {}
extension FfiArrowhead: Equatable, Hashable {
    public static func == (lhs: FfiArrowhead, rhs: FfiArrowhead) -> Bool {
        if lhs.tip != rhs.tip {
            return false
        }
        if lhs.angle != rhs.angle {
            return false
        }
        if lhs.left != rhs.left {
            return false
        }
        if lhs.right != rhs.right {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(tip)
        hasher.combine(angle)
        hasher.combine(left)
        hasher.combine(right)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiArrowhead: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiArrowhead {
        return
            try FfiArrowhead(
                tip: FfiConverterTypeFfiPoint.read(from: &buf),
                angle: FfiConverterFloat.read(from: &buf),
                left: FfiConverterTypeFfiPoint.read(from: &buf),
                right: FfiConverterTypeFfiPoint.read(from: &buf)
            )
    }

    public static func write(_ value: FfiArrowhead, into buf: inout [UInt8]) {
        FfiConverterTypeFfiPoint.write(value.tip, into: &buf)
        FfiConverterFloat.write(value.angle, into: &buf)
        FfiConverterTypeFfiPoint.write(value.left, into: &buf)
        FfiConverterTypeFfiPoint.write(value.right, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiArrowhead_lift(_ buf: RustBuffer) throws -> FfiArrowhead {
    return try FfiConverterTypeFfiArrowhead.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiArrowhead_lower(_ value: FfiArrowhead) -> RustBuffer {
    return FfiConverterTypeFfiArrowhead.lower(value)
}

/**
 * Tuning knobs for one `layout()` call.
 */
public struct FfiConfig {
    /**
     * Minimum gap between adjacent siblings' edges (not centers) within a
     * layer.
     */
    public var hGap: Float
    /**
     * Minimum gap between adjacent ranks' edges (not centers).
     */
    public var vGap: Float
    /**
     * Number of median-relaxation passes; ignored when `algorithm` is
     * `BrandesKopf`. Higher values straighten edges further at the cost
     * of more compute.
     */
    public var relaxPasses: UInt32
    /**
     * Barycenter sweep count for crossing reduction. 4 is a reasonable
     * default; raise it for a "final" layout, lower it while the user is
     * interactively editing the graph.
     */
    public var sweeps: UInt32
    /**
     * Which coordinate-assignment algorithm to use.
     */
    public var algorithm: FfiAlgorithm
    /**
     * How to draw edges between their waypoints.
     */
    public var routing: FfiRoutingStyle
    /**
     * Which way the graph flows.
     */
    public var direction: FfiDirection

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Minimum gap between adjacent siblings' edges (not centers) within a
         * layer.
         */ hGap: Float,
        /* 
            * Minimum gap between adjacent ranks' edges (not centers).
            */ vGap: Float,
        /* 
            * Number of median-relaxation passes; ignored when `algorithm` is
            * `BrandesKopf`. Higher values straighten edges further at the cost
            * of more compute.
            */ relaxPasses: UInt32,
        /* 
            * Barycenter sweep count for crossing reduction. 4 is a reasonable
            * default; raise it for a "final" layout, lower it while the user is
            * interactively editing the graph.
            */ sweeps: UInt32,
        /* 
            * Which coordinate-assignment algorithm to use.
            */ algorithm: FfiAlgorithm,
        /* 
            * How to draw edges between their waypoints.
            */ routing: FfiRoutingStyle,
        /* 
            * Which way the graph flows.
            */ direction: FfiDirection
    ) {
        self.hGap = hGap
        self.vGap = vGap
        self.relaxPasses = relaxPasses
        self.sweeps = sweeps
        self.algorithm = algorithm
        self.routing = routing
        self.direction = direction
    }
}

extension FfiConfig: Sendable {}
extension FfiConfig: Equatable, Hashable {
    public static func == (lhs: FfiConfig, rhs: FfiConfig) -> Bool {
        if lhs.hGap != rhs.hGap {
            return false
        }
        if lhs.vGap != rhs.vGap {
            return false
        }
        if lhs.relaxPasses != rhs.relaxPasses {
            return false
        }
        if lhs.sweeps != rhs.sweeps {
            return false
        }
        if lhs.algorithm != rhs.algorithm {
            return false
        }
        if lhs.routing != rhs.routing {
            return false
        }
        if lhs.direction != rhs.direction {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(hGap)
        hasher.combine(vGap)
        hasher.combine(relaxPasses)
        hasher.combine(sweeps)
        hasher.combine(algorithm)
        hasher.combine(routing)
        hasher.combine(direction)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiConfig {
        return
            try FfiConfig(
                hGap: FfiConverterFloat.read(from: &buf),
                vGap: FfiConverterFloat.read(from: &buf),
                relaxPasses: FfiConverterUInt32.read(from: &buf),
                sweeps: FfiConverterUInt32.read(from: &buf),
                algorithm: FfiConverterTypeFfiAlgorithm.read(from: &buf),
                routing: FfiConverterTypeFfiRoutingStyle.read(from: &buf),
                direction: FfiConverterTypeFfiDirection.read(from: &buf)
            )
    }

    public static func write(_ value: FfiConfig, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.hGap, into: &buf)
        FfiConverterFloat.write(value.vGap, into: &buf)
        FfiConverterUInt32.write(value.relaxPasses, into: &buf)
        FfiConverterUInt32.write(value.sweeps, into: &buf)
        FfiConverterTypeFfiAlgorithm.write(value.algorithm, into: &buf)
        FfiConverterTypeFfiRoutingStyle.write(value.routing, into: &buf)
        FfiConverterTypeFfiDirection.write(value.direction, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiConfig_lift(_ buf: RustBuffer) throws -> FfiConfig {
    return try FfiConverterTypeFfiConfig.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiConfig_lower(_ value: FfiConfig) -> RustBuffer {
    return FfiConverterTypeFfiConfig.lower(value)
}

/**
 * A single edge, referencing nodes by the caller's own opaque ids.
 */
public struct FfiEdge {
    /**
     * Stable caller-assigned edge identity, echoed in `FfiEdgeRoute`.
     */
    public var id: UInt64
    /**
     * Source node's caller-assigned id.
     */
    public var from: UInt64
    /**
     * Target node's caller-assigned id.
     */
    public var to: UInt64
    /**
     * Optional label width for obstacle-free label placement.
     */
    public var labelWidth: Float?
    /**
     * Optional label height for obstacle-free label placement.
     */
    public var labelHeight: Float?

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Stable caller-assigned edge identity, echoed in `FfiEdgeRoute`.
         */ id: UInt64,
        /* 
            * Source node's caller-assigned id.
            */ from: UInt64,
        /* 
            * Target node's caller-assigned id.
            */ to: UInt64,
        /* 
            * Optional label width for obstacle-free label placement.
            */ labelWidth: Float?,
        /* 
            * Optional label height for obstacle-free label placement.
            */ labelHeight: Float?
    ) {
        self.id = id
        self.from = from
        self.to = to
        self.labelWidth = labelWidth
        self.labelHeight = labelHeight
    }
}

extension FfiEdge: Sendable {}
extension FfiEdge: Equatable, Hashable {
    public static func == (lhs: FfiEdge, rhs: FfiEdge) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.from != rhs.from {
            return false
        }
        if lhs.to != rhs.to {
            return false
        }
        if lhs.labelWidth != rhs.labelWidth {
            return false
        }
        if lhs.labelHeight != rhs.labelHeight {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(from)
        hasher.combine(to)
        hasher.combine(labelWidth)
        hasher.combine(labelHeight)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEdge: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEdge {
        return
            try FfiEdge(
                id: FfiConverterUInt64.read(from: &buf),
                from: FfiConverterUInt64.read(from: &buf),
                to: FfiConverterUInt64.read(from: &buf),
                labelWidth: FfiConverterOptionFloat.read(from: &buf),
                labelHeight: FfiConverterOptionFloat.read(from: &buf)
            )
    }

    public static func write(_ value: FfiEdge, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.id, into: &buf)
        FfiConverterUInt64.write(value.from, into: &buf)
        FfiConverterUInt64.write(value.to, into: &buf)
        FfiConverterOptionFloat.write(value.labelWidth, into: &buf)
        FfiConverterOptionFloat.write(value.labelHeight, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEdge_lift(_ buf: RustBuffer) throws -> FfiEdge {
    return try FfiConverterTypeFfiEdge.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEdge_lower(_ value: FfiEdge) -> RustBuffer {
    return FfiConverterTypeFfiEdge.lower(value)
}

/**
 * A single edge's final routed path, keyed by the caller's own ids.
 */
public struct FfiEdgeRoute {
    /**
     * Stable caller-assigned identity from `FfiEdge::id`.
     */
    public var id: UInt64
    /**
     * Source node's caller-assigned id, as given in `FfiEdge::from`.
     */
    public var from: UInt64
    /**
     * Target node's caller-assigned id, as given in `FfiEdge::to`.
     */
    public var to: UInt64
    /**
     * True if this edge was reversed by cycle breaking; draw the
     * arrowhead at the `from` end rather than the `to` end.
     */
    public var reversed: Bool
    /**
     * Whether this route represents a self-loop (`from == to`).
     */
    public var isSelfLoop: Bool
    /**
     * Waypoints from source to target — see `EdgeRoute::waypoints` for
     * how these are packed per `routing` style.
     */
    public var waypoints: [FfiPoint]
    /**
     * The same path as `waypoints`, decomposed into explicit line/curve
     * segments — use this instead of `waypoints` if you'd rather not
     * re-derive segment boundaries from the routing style yourself.
     */
    public var segments: [FfiPathSegment]
    /**
     * Precomputed arrowhead geometry (tip + wing vertices) at the target end.
     */
    public var arrowhead: FfiArrowhead?
    /**
     * Obstacle-free label center position, if the edge had label dimensions.
     */
    public var labelPosition: FfiPoint?

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Stable caller-assigned identity from `FfiEdge::id`.
         */ id: UInt64,
        /* 
            * Source node's caller-assigned id, as given in `FfiEdge::from`.
            */ from: UInt64,
        /* 
            * Target node's caller-assigned id, as given in `FfiEdge::to`.
            */ to: UInt64,
        /* 
            * True if this edge was reversed by cycle breaking; draw the
            * arrowhead at the `from` end rather than the `to` end.
            */ reversed: Bool,
        /* 
            * Whether this route represents a self-loop (`from == to`).
            */ isSelfLoop: Bool,
        /* 
            * Waypoints from source to target — see `EdgeRoute::waypoints` for
            * how these are packed per `routing` style.
            */ waypoints: [FfiPoint],
        /* 
            * The same path as `waypoints`, decomposed into explicit line/curve
            * segments — use this instead of `waypoints` if you'd rather not
            * re-derive segment boundaries from the routing style yourself.
            */ segments: [FfiPathSegment],
        /* 
            * Precomputed arrowhead geometry (tip + wing vertices) at the target end.
            */ arrowhead: FfiArrowhead?,
        /* 
            * Obstacle-free label center position, if the edge had label dimensions.
            */ labelPosition: FfiPoint?
    ) {
        self.id = id
        self.from = from
        self.to = to
        self.reversed = reversed
        self.isSelfLoop = isSelfLoop
        self.waypoints = waypoints
        self.segments = segments
        self.arrowhead = arrowhead
        self.labelPosition = labelPosition
    }
}

extension FfiEdgeRoute: Sendable {}
extension FfiEdgeRoute: Equatable, Hashable {
    public static func == (lhs: FfiEdgeRoute, rhs: FfiEdgeRoute) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.from != rhs.from {
            return false
        }
        if lhs.to != rhs.to {
            return false
        }
        if lhs.reversed != rhs.reversed {
            return false
        }
        if lhs.isSelfLoop != rhs.isSelfLoop {
            return false
        }
        if lhs.waypoints != rhs.waypoints {
            return false
        }
        if lhs.segments != rhs.segments {
            return false
        }
        if lhs.arrowhead != rhs.arrowhead {
            return false
        }
        if lhs.labelPosition != rhs.labelPosition {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(from)
        hasher.combine(to)
        hasher.combine(reversed)
        hasher.combine(isSelfLoop)
        hasher.combine(waypoints)
        hasher.combine(segments)
        hasher.combine(arrowhead)
        hasher.combine(labelPosition)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEdgeRoute: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEdgeRoute {
        return
            try FfiEdgeRoute(
                id: FfiConverterUInt64.read(from: &buf),
                from: FfiConverterUInt64.read(from: &buf),
                to: FfiConverterUInt64.read(from: &buf),
                reversed: FfiConverterBool.read(from: &buf),
                isSelfLoop: FfiConverterBool.read(from: &buf),
                waypoints: FfiConverterSequenceTypeFfiPoint.read(from: &buf),
                segments: FfiConverterSequenceTypeFfiPathSegment.read(from: &buf),
                arrowhead: FfiConverterOptionTypeFfiArrowhead.read(from: &buf),
                labelPosition: FfiConverterOptionTypeFfiPoint.read(from: &buf)
            )
    }

    public static func write(_ value: FfiEdgeRoute, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.id, into: &buf)
        FfiConverterUInt64.write(value.from, into: &buf)
        FfiConverterUInt64.write(value.to, into: &buf)
        FfiConverterBool.write(value.reversed, into: &buf)
        FfiConverterBool.write(value.isSelfLoop, into: &buf)
        FfiConverterSequenceTypeFfiPoint.write(value.waypoints, into: &buf)
        FfiConverterSequenceTypeFfiPathSegment.write(value.segments, into: &buf)
        FfiConverterOptionTypeFfiArrowhead.write(value.arrowhead, into: &buf)
        FfiConverterOptionTypeFfiPoint.write(value.labelPosition, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEdgeRoute_lift(_ buf: RustBuffer) throws -> FfiEdgeRoute {
    return try FfiConverterTypeFfiEdgeRoute.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEdgeRoute_lower(_ value: FfiEdgeRoute) -> RustBuffer {
    return FfiConverterTypeFfiEdgeRoute.lower(value)
}

/**
 * Everything `layout()` returns for one graph.
 */
public struct FfiLayoutResult {
    /**
     * Every input node's final position, keyed by the caller's own id.
     */
    public var positions: [FfiPosition]
    /**
     * Every input edge's final routed path, including self-loops.
     */
    public var routes: [FfiEdgeRoute]
    /**
     * Original self-loop records, retained as convenient metadata in
     * addition to their routed entries in `routes`.
     */
    public var selfLoops: [FfiEdge]
    /**
     * The graph's overall bounding box, accounting for each node's real
     * width/height and every route waypoint.
     */
    public var bounds: FfiRect

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Every input node's final position, keyed by the caller's own id.
         */ positions: [FfiPosition],
        /* 
            * Every input edge's final routed path, including self-loops.
            */ routes: [FfiEdgeRoute],
        /* 
            * Original self-loop records, retained as convenient metadata in
            * addition to their routed entries in `routes`.
            */ selfLoops: [FfiEdge],
        /* 
            * The graph's overall bounding box, accounting for each node's real
            * width/height and every route waypoint.
            */ bounds: FfiRect
    ) {
        self.positions = positions
        self.routes = routes
        self.selfLoops = selfLoops
        self.bounds = bounds
    }
}

extension FfiLayoutResult: Sendable {}
extension FfiLayoutResult: Equatable, Hashable {
    public static func == (lhs: FfiLayoutResult, rhs: FfiLayoutResult) -> Bool {
        if lhs.positions != rhs.positions {
            return false
        }
        if lhs.routes != rhs.routes {
            return false
        }
        if lhs.selfLoops != rhs.selfLoops {
            return false
        }
        if lhs.bounds != rhs.bounds {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(positions)
        hasher.combine(routes)
        hasher.combine(selfLoops)
        hasher.combine(bounds)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiLayoutResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiLayoutResult {
        return
            try FfiLayoutResult(
                positions: FfiConverterSequenceTypeFfiPosition.read(from: &buf),
                routes: FfiConverterSequenceTypeFfiEdgeRoute.read(from: &buf),
                selfLoops: FfiConverterSequenceTypeFfiEdge.read(from: &buf),
                bounds: FfiConverterTypeFfiRect.read(from: &buf)
            )
    }

    public static func write(_ value: FfiLayoutResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiPosition.write(value.positions, into: &buf)
        FfiConverterSequenceTypeFfiEdgeRoute.write(value.routes, into: &buf)
        FfiConverterSequenceTypeFfiEdge.write(value.selfLoops, into: &buf)
        FfiConverterTypeFfiRect.write(value.bounds, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiLayoutResult_lift(_ buf: RustBuffer) throws -> FfiLayoutResult {
    return try FfiConverterTypeFfiLayoutResult.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiLayoutResult_lower(_ value: FfiLayoutResult) -> RustBuffer {
    return FfiConverterTypeFfiLayoutResult.lower(value)
}

/**
 * A single node, keyed by the caller's own opaque id (not necessarily
 * dense or zero-based — see the module docs for why).
 */
public struct FfiNode {
    /**
     * The caller's own id for this node. Echoed back in `FfiPosition`
     * and every `FfiEdgeRoute`/`FfiEdge` that touches it.
     */
    public var id: UInt64
    /**
     * Visual width, used by coordinate assignment's separation math.
     */
    public var width: Float
    /**
     * Visual height, used by coordinate assignment's separation math.
     */
    public var height: Float
    /**
     * Optional requested rank.
     */
    public var rankHint: UInt32?
    /**
     * Interpretation of `rank_hint` when it is present.
     */
    public var rankConstraint: FfiRankConstraint

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The caller's own id for this node. Echoed back in `FfiPosition`
         * and every `FfiEdgeRoute`/`FfiEdge` that touches it.
         */ id: UInt64,
        /* 
            * Visual width, used by coordinate assignment's separation math.
            */ width: Float,
        /* 
            * Visual height, used by coordinate assignment's separation math.
            */ height: Float,
        /* 
            * Optional requested rank.
            */ rankHint: UInt32?,
        /* 
            * Interpretation of `rank_hint` when it is present.
            */ rankConstraint: FfiRankConstraint
    ) {
        self.id = id
        self.width = width
        self.height = height
        self.rankHint = rankHint
        self.rankConstraint = rankConstraint
    }
}

extension FfiNode: Sendable {}
extension FfiNode: Equatable, Hashable {
    public static func == (lhs: FfiNode, rhs: FfiNode) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.rankHint != rhs.rankHint {
            return false
        }
        if lhs.rankConstraint != rhs.rankConstraint {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(rankHint)
        hasher.combine(rankConstraint)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiNode: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNode {
        return
            try FfiNode(
                id: FfiConverterUInt64.read(from: &buf),
                width: FfiConverterFloat.read(from: &buf),
                height: FfiConverterFloat.read(from: &buf),
                rankHint: FfiConverterOptionUInt32.read(from: &buf),
                rankConstraint: FfiConverterTypeFfiRankConstraint.read(from: &buf)
            )
    }

    public static func write(_ value: FfiNode, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.id, into: &buf)
        FfiConverterFloat.write(value.width, into: &buf)
        FfiConverterFloat.write(value.height, into: &buf)
        FfiConverterOptionUInt32.write(value.rankHint, into: &buf)
        FfiConverterTypeFfiRankConstraint.write(value.rankConstraint, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNode_lift(_ buf: RustBuffer) throws -> FfiNode {
    return try FfiConverterTypeFfiNode.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNode_lower(_ value: FfiNode) -> RustBuffer {
    return FfiConverterTypeFfiNode.lower(value)
}

/**
 * A 2D point in the layout's own coordinate space (origin-centered — see
 * the `Swift-Layout` README for how a consumer maps this onto a canvas).
 */
public struct FfiPoint {
    /**
     * X coordinate.
     */
    public var x: Float
    /**
     * Y coordinate.
     */
    public var y: Float

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * X coordinate.
         */ x: Float,
        /* 
            * Y coordinate.
            */ y: Float
    ) {
        self.x = x
        self.y = y
    }
}

extension FfiPoint: Sendable {}
extension FfiPoint: Equatable, Hashable {
    public static func == (lhs: FfiPoint, rhs: FfiPoint) -> Bool {
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x)
        hasher.combine(y)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPoint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPoint {
        return
            try FfiPoint(
                x: FfiConverterFloat.read(from: &buf),
                y: FfiConverterFloat.read(from: &buf)
            )
    }

    public static func write(_ value: FfiPoint, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.x, into: &buf)
        FfiConverterFloat.write(value.y, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPoint_lift(_ buf: RustBuffer) throws -> FfiPoint {
    return try FfiConverterTypeFfiPoint.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPoint_lower(_ value: FfiPoint) -> RustBuffer {
    return FfiConverterTypeFfiPoint.lower(value)
}

/**
 * A node's final assigned position, keyed by the caller's own id.
 */
public struct FfiPosition {
    /**
     * The caller's own id for this node, as given in `FfiNode::id`.
     */
    public var id: UInt64
    /**
     * Assigned x coordinate.
     */
    public var x: Float
    /**
     * Assigned y coordinate.
     */
    public var y: Float
    /**
     * Assigned, uncompressed rank number.
     */
    public var rank: UInt32

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * The caller's own id for this node, as given in `FfiNode::id`.
         */ id: UInt64,
        /* 
            * Assigned x coordinate.
            */ x: Float,
        /* 
            * Assigned y coordinate.
            */ y: Float,
        /* 
            * Assigned, uncompressed rank number.
            */ rank: UInt32
    ) {
        self.id = id
        self.x = x
        self.y = y
        self.rank = rank
    }
}

extension FfiPosition: Sendable {}
extension FfiPosition: Equatable, Hashable {
    public static func == (lhs: FfiPosition, rhs: FfiPosition) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        if lhs.rank != rhs.rank {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(x)
        hasher.combine(y)
        hasher.combine(rank)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPosition: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPosition {
        return
            try FfiPosition(
                id: FfiConverterUInt64.read(from: &buf),
                x: FfiConverterFloat.read(from: &buf),
                y: FfiConverterFloat.read(from: &buf),
                rank: FfiConverterUInt32.read(from: &buf)
            )
    }

    public static func write(_ value: FfiPosition, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.id, into: &buf)
        FfiConverterFloat.write(value.x, into: &buf)
        FfiConverterFloat.write(value.y, into: &buf)
        FfiConverterUInt32.write(value.rank, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPosition_lift(_ buf: RustBuffer) throws -> FfiPosition {
    return try FfiConverterTypeFfiPosition.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPosition_lower(_ value: FfiPosition) -> RustBuffer {
    return FfiConverterTypeFfiPosition.lower(value)
}

/**
 * An axis-aligned bounding box, accounting for each node's actual
 * width/height (not just its center) — see [`FfiLayoutResult::bounds`].
 */
public struct FfiRect {
    /**
     * Minimum x across every node and route waypoint.
     */
    public var minX: Float
    /**
     * Minimum y across every node and route waypoint.
     */
    public var minY: Float
    /**
     * Maximum x across every node and route waypoint.
     */
    public var maxX: Float
    /**
     * Maximum y across every node and route waypoint.
     */
    public var maxY: Float
    /**
     * `max_x - min_x`.
     */
    public var width: Float
    /**
     * `max_y - min_y`.
     */
    public var height: Float

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(
        /* 
         * Minimum x across every node and route waypoint.
         */ minX: Float,
        /* 
            * Minimum y across every node and route waypoint.
            */ minY: Float,
        /* 
            * Maximum x across every node and route waypoint.
            */ maxX: Float,
        /* 
            * Maximum y across every node and route waypoint.
            */ maxY: Float,
        /* 
            * `max_x - min_x`.
            */ width: Float,
        /* 
            * `max_y - min_y`.
            */ height: Float
    ) {
        self.minX = minX
        self.minY = minY
        self.maxX = maxX
        self.maxY = maxY
        self.width = width
        self.height = height
    }
}

extension FfiRect: Sendable {}
extension FfiRect: Equatable, Hashable {
    public static func == (lhs: FfiRect, rhs: FfiRect) -> Bool {
        if lhs.minX != rhs.minX {
            return false
        }
        if lhs.minY != rhs.minY {
            return false
        }
        if lhs.maxX != rhs.maxX {
            return false
        }
        if lhs.maxY != rhs.maxY {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(minX)
        hasher.combine(minY)
        hasher.combine(maxX)
        hasher.combine(maxY)
        hasher.combine(width)
        hasher.combine(height)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRect: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRect {
        return
            try FfiRect(
                minX: FfiConverterFloat.read(from: &buf),
                minY: FfiConverterFloat.read(from: &buf),
                maxX: FfiConverterFloat.read(from: &buf),
                maxY: FfiConverterFloat.read(from: &buf),
                width: FfiConverterFloat.read(from: &buf),
                height: FfiConverterFloat.read(from: &buf)
            )
    }

    public static func write(_ value: FfiRect, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.minX, into: &buf)
        FfiConverterFloat.write(value.minY, into: &buf)
        FfiConverterFloat.write(value.maxX, into: &buf)
        FfiConverterFloat.write(value.maxY, into: &buf)
        FfiConverterFloat.write(value.width, into: &buf)
        FfiConverterFloat.write(value.height, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRect_lift(_ buf: RustBuffer) throws -> FfiRect {
    return try FfiConverterTypeFfiRect.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRect_lower(_ value: FfiRect) -> RustBuffer {
    return FfiConverterTypeFfiRect.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Mirrors [`CoordAlgorithm`] across the FFI boundary.
 */

public enum FfiAlgorithm {
    /**
     * Weighted median relaxation with compaction (simpler, O(N·passes)).
     */
    case medianRelax
    /**
     * Brandes-Köpf alignment averaging (better quality, O(N)).
     */
    case brandesKopf
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAlgorithm: FfiConverterRustBuffer {
    typealias SwiftType = FfiAlgorithm

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAlgorithm {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .medianRelax

        case 2: return .brandesKopf

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiAlgorithm, into buf: inout [UInt8]) {
        switch value {
        case .medianRelax:
            writeInt(&buf, Int32(1))

        case .brandesKopf:
            writeInt(&buf, Int32(2))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAlgorithm_lift(_ buf: RustBuffer) throws -> FfiAlgorithm {
    return try FfiConverterTypeFfiAlgorithm.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAlgorithm_lower(_ value: FfiAlgorithm) -> RustBuffer {
    return FfiConverterTypeFfiAlgorithm.lower(value)
}

extension FfiAlgorithm: Sendable {}
extension FfiAlgorithm: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Mirrors [`LayoutDirection`] across the FFI boundary.
 */

public enum FfiDirection {
    /**
     * Rank 0 at the top, increasing ranks flow downward.
     */
    case topToBottom
    /**
     * Rank 0 at the left, increasing ranks flow rightward.
     */
    case leftToRight
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDirection: FfiConverterRustBuffer {
    typealias SwiftType = FfiDirection

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDirection {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .topToBottom

        case 2: return .leftToRight

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiDirection, into buf: inout [UInt8]) {
        switch value {
        case .topToBottom:
            writeInt(&buf, Int32(1))

        case .leftToRight:
            writeInt(&buf, Int32(2))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDirection_lift(_ buf: RustBuffer) throws -> FfiDirection {
    return try FfiConverterTypeFfiDirection.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDirection_lower(_ value: FfiDirection) -> RustBuffer {
    return FfiConverterTypeFfiDirection.lower(value)
}

extension FfiDirection: Sendable {}
extension FfiDirection: Equatable, Hashable {}

/**
 * Everything that can go wrong calling `layout()` — either the input
 * graph was invalid, or the engine panicked internally (a bug, not bad
 * input; see the variant docs).
 */
public enum FfiLayoutError {
    /**
     * The input graph itself was invalid: a duplicate/unknown node id, or
     * (from `LayoutError`) a genuine cycle that survived cycle breaking.
     */
    case InvalidGraph(message: String)

    /**
     * The layout engine panicked internally. This is always a bug in the
     * engine, not bad input — please report it with the graph that
     * triggered it.
     */
    case Internal(message: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiLayoutError: FfiConverterRustBuffer {
    typealias SwiftType = FfiLayoutError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiLayoutError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .InvalidGraph(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .Internal(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiLayoutError, into buf: inout [UInt8]) {
        switch value {
        case .InvalidGraph(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .Internal(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        }
    }
}

extension FfiLayoutError: Equatable, Hashable {}

extension FfiLayoutError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * One segment of a routed edge's path, as an explicit drawing primitive
 * (an alternative to walking `FfiEdgeRoute::waypoints` yourself and
 * guessing which style connects them).
 */

public enum FfiPathSegment {
    /**
     * A straight line between two points.
     */
    case line(
        /* 
         * Segment start point.
         */ start: FfiPoint,
        /* 
            * Segment end point.
            */ end: FfiPoint
    )
    /**
     * A cubic bezier curve between two points with two control points.
     */
    case cubicCurve(
        /* 
         * Curve start point.
         */ start: FfiPoint,
        /* 
            * First control point.
            */ control1: FfiPoint,
        /* 
            * Second control point.
            */ control2: FfiPoint,
        /* 
            * Curve end point.
            */ end: FfiPoint
    )
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPathSegment: FfiConverterRustBuffer {
    typealias SwiftType = FfiPathSegment

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPathSegment {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .line(start: FfiConverterTypeFfiPoint.read(from: &buf), end: FfiConverterTypeFfiPoint.read(from: &buf))

        case 2: return try .cubicCurve(start: FfiConverterTypeFfiPoint.read(from: &buf), control1: FfiConverterTypeFfiPoint.read(from: &buf), control2: FfiConverterTypeFfiPoint.read(from: &buf), end: FfiConverterTypeFfiPoint.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiPathSegment, into buf: inout [UInt8]) {
        switch value {
        case let .line(start, end):
            writeInt(&buf, Int32(1))
            FfiConverterTypeFfiPoint.write(start, into: &buf)
            FfiConverterTypeFfiPoint.write(end, into: &buf)

        case let .cubicCurve(start, control1, control2, end):
            writeInt(&buf, Int32(2))
            FfiConverterTypeFfiPoint.write(start, into: &buf)
            FfiConverterTypeFfiPoint.write(control1, into: &buf)
            FfiConverterTypeFfiPoint.write(control2, into: &buf)
            FfiConverterTypeFfiPoint.write(end, into: &buf)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPathSegment_lift(_ buf: RustBuffer) throws -> FfiPathSegment {
    return try FfiConverterTypeFfiPathSegment.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPathSegment_lower(_ value: FfiPathSegment) -> RustBuffer {
    return FfiConverterTypeFfiPathSegment.lower(value)
}

extension FfiPathSegment: Sendable {}
extension FfiPathSegment: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Whether a rank hint is flexible guidance or an exact requirement.
 */

public enum FfiRankConstraint {
    /**
     * Preserve the hinted rank when possible, but move later if required.
     */
    case preferred
    /**
     * Require the exact hinted rank and reject infeasible graphs.
     */
    case pinned
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRankConstraint: FfiConverterRustBuffer {
    typealias SwiftType = FfiRankConstraint

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRankConstraint {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .preferred

        case 2: return .pinned

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiRankConstraint, into buf: inout [UInt8]) {
        switch value {
        case .preferred:
            writeInt(&buf, Int32(1))

        case .pinned:
            writeInt(&buf, Int32(2))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRankConstraint_lift(_ buf: RustBuffer) throws -> FfiRankConstraint {
    return try FfiConverterTypeFfiRankConstraint.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRankConstraint_lower(_ value: FfiRankConstraint) -> RustBuffer {
    return FfiConverterTypeFfiRankConstraint.lower(value)
}

extension FfiRankConstraint: Sendable {}
extension FfiRankConstraint: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Mirrors [`RoutingStyle`] across the FFI boundary.
 */

public enum FfiRoutingStyle {
    /**
     * Straight line, 2 points only — ignores any dummy waypoints.
     */
    case straight
    /**
     * Right-angle polyline through dummy midpoints.
     */
    case orthogonal
    /**
     * Smooth cubic bezier through dummy waypoints.
     */
    case bezier
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRoutingStyle: FfiConverterRustBuffer {
    typealias SwiftType = FfiRoutingStyle

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRoutingStyle {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .straight

        case 2: return .orthogonal

        case 3: return .bezier

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiRoutingStyle, into buf: inout [UInt8]) {
        switch value {
        case .straight:
            writeInt(&buf, Int32(1))

        case .orthogonal:
            writeInt(&buf, Int32(2))

        case .bezier:
            writeInt(&buf, Int32(3))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRoutingStyle_lift(_ buf: RustBuffer) throws -> FfiRoutingStyle {
    return try FfiConverterTypeFfiRoutingStyle.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRoutingStyle_lower(_ value: FfiRoutingStyle) -> RustBuffer {
    return FfiConverterTypeFfiRoutingStyle.lower(value)
}

extension FfiRoutingStyle: Sendable {}
extension FfiRoutingStyle: Equatable, Hashable {}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionFloat: FfiConverterRustBuffer {
    typealias SwiftType = Float?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterFloat.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterFloat.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeFfiArrowhead: FfiConverterRustBuffer {
    typealias SwiftType = FfiArrowhead?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiArrowhead.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiArrowhead.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionTypeFfiPoint: FfiConverterRustBuffer {
    typealias SwiftType = FfiPoint?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiPoint.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiPoint.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceUInt64: FfiConverterRustBuffer {
    typealias SwiftType = [UInt64]

    static func write(_ value: [UInt64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt64.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt64] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterUInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeFfiEdge: FfiConverterRustBuffer {
    typealias SwiftType = [FfiEdge]

    static func write(_ value: [FfiEdge], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiEdge.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiEdge] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiEdge]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeFfiEdge.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeFfiEdgeRoute: FfiConverterRustBuffer {
    typealias SwiftType = [FfiEdgeRoute]

    static func write(_ value: [FfiEdgeRoute], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiEdgeRoute.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiEdgeRoute] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiEdgeRoute]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeFfiEdgeRoute.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeFfiNode: FfiConverterRustBuffer {
    typealias SwiftType = [FfiNode]

    static func write(_ value: [FfiNode], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiNode.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiNode] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiNode]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeFfiNode.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeFfiPoint: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPoint]

    static func write(_ value: [FfiPoint], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPoint.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPoint] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPoint]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeFfiPoint.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeFfiPosition: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPosition]

    static func write(_ value: [FfiPosition], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPosition.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPosition] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPosition]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeFfiPosition.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterSequenceTypeFfiPathSegment: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPathSegment]

    static func write(_ value: [FfiPathSegment], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPathSegment.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPathSegment] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPathSegment]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeFfiPathSegment.read(from: &buf))
        }
        return seq
    }
}

/**
 * Runs the full layout pipeline (cycle breaking through edge routing) in
 * one call and returns final node positions and edge routes, keyed on the
 * caller's own `u64` node ids.
 */
public func layout(nodes: [FfiNode], edges: [FfiEdge], config: FfiConfig) throws -> FfiLayoutResult {
    return try FfiConverterTypeFfiLayoutResult.lift(rustCallWithError(FfiConverterTypeFfiLayoutError.lift) {
        uniffi_layout_fn_func_layout(
            FfiConverterSequenceTypeFfiNode.lower(nodes),
            FfiConverterSequenceTypeFfiEdge.lower(edges),
            FfiConverterTypeFfiConfig.lower(config), $0
        )
    })
}

/**
 * Lays out a validated bipartite graph with the first partition pinned to
 * rank 0 and the second pinned to rank 1. Cycle breaking is deliberately
 * bypassed; edges are normalized from the first partition to the second.
 * Set `directed` to preserve directed edge orientation instead.
 * `max_iterations == 0` selects the default cap of eight full iterations.
 */
public func layoutBipartite(nodes: [FfiNode], edges: [FfiEdge], partitionU: [UInt64], partitionV: [UInt64], directed: Bool, maxIterations: UInt32, config: FfiConfig) throws -> FfiLayoutResult {
    return try FfiConverterTypeFfiLayoutResult.lift(rustCallWithError(FfiConverterTypeFfiLayoutError.lift) {
        uniffi_layout_fn_func_layout_bipartite(
            FfiConverterSequenceTypeFfiNode.lower(nodes),
            FfiConverterSequenceTypeFfiEdge.lower(edges),
            FfiConverterSequenceUInt64.lower(partitionU),
            FfiConverterSequenceUInt64.lower(partitionV),
            FfiConverterBool.lower(directed),
            FfiConverterUInt32.lower(maxIterations),
            FfiConverterTypeFfiConfig.lower(config), $0
        )
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_layout_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_layout_checksum_func_layout() != 43016 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_layout_checksum_func_layout_bipartite() != 55828 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
